### ISSUE TITLE
`get_keyword_pattern` should use `\k` (or `[:keyword:]`) regex instead of `\w`

### ISSUE THREAD

**Issue by cpkio** [quangnguyen30192/cmp-nvim-tags#3]
https://github.com/quangnguyen30192/cmp-nvim-tags/blob/51cb13c2a649d81cd88cbd00654b0998d1ee7fa6/lua/cmp_nvim_tags/init.lua#L57

**Comment by quangnguyen30192** [comment]
Could you provide what the use-case is ?

**Comment by cpkio** [comment]
`\w+` in Vim/Neovim includes ASCII only, not other glyphs. When using `ctags` on cyrillic asciidoc files for example, `\w` works erroneously. Or you should enable `option = { keyword_pattern = [[\k\+]] }` like `github.com/hrsh7th/cmp-buffer` does.

**Comment by cpkio** [comment]
btw `iskeyword` can be different for various filetypes, so `\k` makes more sense. For now you limit `cmp-tags` behaviour.

**Comment by quangnguyen30192** [comment]
Updated
